version: '3.4'

services:
  paymentsapi:
    image: ${DOCKER_REGISTRY-}paymentsapi
    build:
      context: .
      dockerfile: PaymentsAPI/Dockerfile

  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"